apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: o11y

helmCharts:
  - name: signoz
    releaseName: signoz
    namespace: o11y
    repo: https://charts.signoz.io
    valuesFile: values.yaml
    includeCRDs: true
