global:
  storageClass: openebs-hostpath

storageAffinity: &storageAffinity
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage.openebs.io/hostpath
              operator: In
              values:
                - "true"

clickhouse:
  installCustomStorageClass: true
  affinity: *storageAffinity
  zookeeper:
    affinity: *storageAffinity

signoz:
  affinity: *storageAffinity
